import {
    html,
    css,
    sass,
    js,
    ts,
    solidity,
    es6,
    react,
    next,
    redux,
    nodejs,
    json,
    graphql,
    mern,
    figma,
    bootstrap,
    tailwind,
    mui,
    styledcomponent,
    sql,
    mysql,
    mongodb,
    vercel,
    netlify,
    firebase,
    testing,
    smartContract,
    hardhat
} from '../../images/services-pics';

export default [
    { id: 40, name: "SMART CONTRACTS", detail: "Smart Contracts", pic: smartContract },
    { id: 19, name: "MERN STACK", detail: "Full Stack", pic: mern },
    { id: 9, name: "NEXT JS", detail: "ReactJS Framework", pic: next },
    { id: 16, name: "REST API", detail: "API Type", pic: json },
    { id: 5, name: "SOLIDITY", detail: "Programming Language", pic: solidity },
    { id: 4, name: "TYPESCRIPT", detail: "Programming Language", pic: ts },
    { id: 3, name: "JAVASCRIPT", detail: "Programming Language", pic: js },
    { id: 0, name: "HTML", detail: "Markup Language", pic: html },
    { id: 1, name: "CSS", detail: "StyleSheet Language", pic: css },
    { id: 2, name: "SASS", detail: "CSS Preprocessor", pic: sass },
    { id: 6, name: "ECMASCRIPT", detail: "Advanced JavaScript", pic: es6 },
    { id: 11, name: "REDUX", detail: "State Managemnet", pic: redux },
    { id: 12, name: "CONTEXT", detail: "State Managemnet", pic: react },
    { id: 15, name: "NODE JS", detail: "Backend Framework", pic: nodejs },
    { id: 18, name: "GRAPHQL", detail: "API Type", pic: graphql },
    { id: 22, name: "FIGMA", detail: "UI/UX Design", pic: figma },
    { id: 24, name: "BOOTSTRAP", detail: "CSS Framework", pic: bootstrap },
    { id: 25, name: "TAILWIND", detail: "CSS Framework", pic: tailwind },
    { id: 26, name: "MATERIAL UI", detail: "Style Library", pic: mui },
    { id: 28, name: "SQL", detail: "Structured Query Language", pic: sql },
    { id: 30, name: "MYSQL", detail: "SQL Database", pic: mysql },
    { id: 33, name: "MONGODB", detail: "NoSQL Database", pic: mongodb },
    { id: 36, name: "VERCEL", detail: "Deloyment Platform", pic: vercel },
    { id: 37, name: "NETLIFY", detail: "Deloyment Platform", pic: netlify },
    { id: 38, name: "FIREBASE", detail: "Deloyment Platform", pic: firebase },
    { id: 39, name: "TESTING", detail: "Application Testing", pic: testing },
];