import {
    project1,
    project2,
    project5,
    project7,
    project10,
    project11,
    project13,
    project14,
    project16,
    project17,
    project18,
    project19,
    project20,
    project21,
    project22,
    project23,
    project24,
    project25,
    project26,
    project27,
    project28
} from "../../images/projects-pics";

export default [
    {
        id: 1,
        name: "Tugboat Animation",
        technologies: "HTML <b>|</b> CSS <b>|</b> Animation",
        url: "https://tugboatanimation-salman.firebaseapp.com/",
        pic: project1,
    },
    {
        id: 2,
        name: "Simply Recipies",
        technologies: "HTML <b>|</b> CSS <b>|</b> JavaScript",
        url: "https://simplyrecipes-salman.firebaseapp.com/index.html",
        pic: project2,
    },
    {
        id: 5,
        name: "Netflix Clone",
        technologies: "HTML <b>|</b> CSS <b>|</b> JavaScript <b>|</b> Clone",
        url: "https://netflixclone-salman.web.app",
        pic: project5,
    },
    {
        id: 7,
        name: "Frontend Bootcamp",
        technologies:
            "HTML <b>|</b> CSS <b>|</b> JavaScript <b>|</b> Bootstrap",
        url: "https://frontendbootcamp-salman.firebaseapp.com",
        pic: project7,
    },
    {
        id: 16,
        name: "Quiz",
        technologies: "ReactJS <b>|</b> Material-UI <b>|</b> Typescript",
        url: "https://quizusingtypescript-salman.netlify.app",
        pic: project16,
    },
    {
        id: 20,
        name: "Data Analytics",
        technologies: "ReactJS <b>|</b> Tailwind-CSS",
        url: "https://dataanalytics-salman.netlify.app",
        pic: project20,
    },
    {
        id: 10,
        name: "Fake Shop",
        technologies:
            "ReactJS <b>|</b> Redux <b>|</b> SCSS <b>|</b> E-commerce",
        url: "https://fakeshop-salman.netlify.app",
        pic: project10,
    },
    {
        id: 11,
        name: "Shoe Store",
        technologies:
            "ReactJS <b>|</b> Redux <b>|</b> SCSS <b>|</b> E-commerce",
        url: "https://shoestore-salman.netlify.app",
        pic: project11,
    },
    {
        id: 17,
        name: "World Ranks",
        technologies: "NextJS <b>|</b> Module-CSS",
        url: "https://world-ranks-salman.vercel.app",
        pic: project17,
    },
    {
        id: 19,
        name: "Google Clone",
        technologies: "ReactJS <b>|</b> SCSS <b>|</b> Clone",
        url: "https://googleclone-salman.netlify.app",
        pic: project19,
    },
    {
        id: 14,
        name: "Youtube Clone",
        technologies:
            "ReactJS <b>|</b> Material-UI <b>|</b> SCSS <b>|</b> Clone",
        url: "https://youtubeclone-salman.netlify.app",
        pic: project14,
    },
    {
        id: 21,
        name: "GPT Landing Page",
        technologies: "NextJS <b>|</b> Tailwind-CSS",
        url: "https://gpt-3-landing-page-seven.vercel.app",
        pic: project21,
    },
    {
        id: 22,
        name: "Goals App",
        technologies: "MERN <b>|</b> Full-Stack <b>|</b> CSS",
        url: "https://goals-mern-app.vercel.app",
        pic: project22,
    },
    {
        id: 18,
        name: "Real Estate",
        technologies: "NextJS <b>|</b> Chakra-UI",
        url: "https://real-state-salman.vercel.app",
        pic: project18,
    },
    {
        id: 13,
        name: "Netflix Clone",
        technologies: "ReactJS <b>|</b> SCSS <b>|</b> Clone",
        url: "https://netflixclone-salman.netlify.app",
        pic: project13,
    },
    {
        id: 23,
        name: "Memories App",
        technologies: "MERN <b>|</b> Material-UI",
        url: "https://memories-salman.vercel.app",
        pic: project23,
    },
    {
        id: 24,
        name: "Initial Stream",
        technologies: "NextJS <b>|</b> TailwindCSS",
        url: "https://initialstream.vercel.app",
        pic: project24,
    },
    {
        id: 25,
        name: "Life Insurance",
        technologies: "NextJS <b>|</b> TailwindCSS",
        url: "https://life-insurance-gamma.vercel.app/",
        pic: project25,
    },
    {
        id: 26,
        name: "NFT Marketplace",
        technologies: "Web3 <b>|</b> NextJS <b>|</b> GraphQL <b>|</b> Nft",
        url: "https://nft-marketplace-salman.vercel.app/",
        pic: project26,
    },
    {
        id: 27,
        name: "NFT Passport",
        technologies: "Web3 <b>|</b> NextJS <b>|</b> Hardhat <b>|</b> Wagmi <b>|</b> Nft",
        url: "https://blend-botanix.vercel.app/",
        pic: project27,
    },
    {
        id: 28,
        name: "Horesly",
        technologies: "Web3 <b>|</b> NextJS <b>|</b> Hardhat <b>|</b> Wagmi <b>|</b> Nft",
        url: "https://horselyworld.com/",
        pic: project28,
    },
];
