export default [
    {value: "Web3", label: "Web3"},
    {value: "Nft", label: "Nft"},
    {value: "ReactJS", label: "ReactJS"},
    {value: "NextJS", label: "NextJS"},
    {value: "Typescript", label: "Typescript"},
    {value: "TailwindCSS", label: "TailwindCSS"},
    {value: "Bootstrap", label: "Bootstrap"},
    {value: "MaterialUI", label: "MaterialUI"},
    {value: "Redux", label: "Redux"},
    {value: "ContextAPI", label: "ContextAPI"},
    {value: "MongoDB", label: "MongoDB"},
    {value: "Axios", label: "Axios"},
    {value: "GraphQL", label: "GraphQL"},
    {value: "Animation", label: "Animation"},
];